config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'homes#top'
  resources :users, only: [:index, :show, :edit, :update]
  get '/mypage' => 'users#mypage'
  resources :books
  get "home/about" => "homes#about"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

	validates :title, presence: true, length: { maximum:200 }

	validates :body, presence: true, length: { maximum:200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 # 　1:Nの1
  has_many :books, dependent: :destroy
  attachment :profile_image

  validates :name, presence: true, length: { in: 2..20 }

  validates :introduction, allow_blank: true, length: { maximum:50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?


   def after_sign_in_path_for(resource)
    user_path(resource)
   end


  private


    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:name, :email])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	before_action :authenticate_user!

	def index
		@books = Book.all
		@book = Book.new
		@user = User.find(current_user.id)
		@users = User.all
	end


	def create
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		if @book.save(book_params)
			redirect_to book_path(@book), notice: 'You have creatad book successfully.'
		else
			@user = User.find(current_user.id)
		    @books = Book.all
		    @users = User.all
			render "index"
		end
	end

	def show
		@books = Book.all
		@booker = Book.find(params[:id])
		@book = Book.new
		@user = User.find(current_user.id)
	end

	def edit
		@book = Book.find(params[:id])
	    unless @book.user == current_user
	     redirect_to books_path
	    end
	end

	def update
		@book = Book.find(params[:id])
	  	if @book.update(book_params)
	    redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
		else
			render "edit"
		end
	end

	def destroy
		@book = Book.find(params[:id])
		if book.destroy
	  	redirect_to books_path, notice: "Book was successfully destroyed."
	    end
	end

	private

	def book_params
		params.require(:book).permit(:title, :body)
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticate_user!
	# 開けるのはログインしているユーザーのみ


  # All Users
  def index
  	@users = User.all
    @user = current_user
    @book = Book.new
  end


  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def mypage
  	redirect_to user_path(current_user)
  end

  def edit
  	# 編集するユーザーが本人じゃない場合はユーザーページにリダイレクトする
    # これをしないと、ログインさえしていれば、"/users/5/edit"みたいな適当なurlにアクセスすると、他の人のプロフィール編集画面を表示できてしまう
    @user = User.find(params[:id])
    if current_user != @user
      redirect_to user_path(current_user.id)
    end
  end

  def update
	 # アップデートがうまくいけば、マイページに戻利、
	 # うまくいかなければ、もう一度編集ページを表示する
	 @user = User.find(params[:id])
	 if @user.update(user_params)
	    redirect_to user_path(@user), notice: 'You have updated user successfully.'
	 else
	    render 'edit'
     end
  end

  private

  def user_params
     params.require(:user).permit(:name, :introduction, :profile_image)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
	<div class="row">
		<div class="col-xs-6 col-xs-offset-3">
			<h1>Editing Book</h1>
			<%= form_for(@book) do |f| %>
				<!-- error message -->
				<% if @book.errors.any? %>
					<div id="error_explanation" class="alert alert-danger">
						<h2><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h2>
					  <ul>
					    <% @book.errors.full_messages.each do |message| %>
					      <li><%= message %></li>
					    <% end %>
					  </ul>
					</div>
				<% end %>
				<div class="book-form row">
					<label>Title</label>
					<%= f.text_field :title, class: "col-xs-12" %>
				</div>
				<div class="book-form row">
					<label>Option</label>
					<%= f.text_area :body, class: "col-xs-12" %>
				</div>
				<div class="book-form row">
					<%= f.submit "Update Book", class: "btn btn-primary col-xs-12" %>
				</div>
			<% end %>

			<%= link_to 'Show', book_path %>
			<span>|</span>
			<%= link_to 'Back', books_path %>
		</div>
	</div>

app/views/books/index.html.erb
<%= render 'users/sidemenu', {user:@user, book:@book} %>

		<div class="col-xs-9">
			<!-- 全ての本 -->
			<div class="books">
			  <h2>Books</h2>
			  <table class="table table-hover">
			    <thead>
			      <tr>
			        <th></th>
			        <th>Title</th>
			        <th>Opinion</th>
			      </tr>
			    </thead>
			    <tbody>
			    	<% @books.each do |book| %>
			      <tr>
			        <td><%= link_to user_path(book.user) do %>
			        	<%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" , size: '40x40'%>
		        		<% end %>
		        	</td>
			        <td><%= link_to(book.title, "/books/#{book.id}") %></td>
			        <td><%= book.body %></td>
			      </tr>
			      <% end %>
			    </tbody>
			  </table>
			</div>

		</div>
	</div>

app/views/books/show.html.erb
	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
			<!-- ユーザー -->
			<div class="user-profile">
				<div class="user-image"><%= attachment_image_tag @booker.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></div>
				 <table class = "table">
			        <tbody>
			          <tr>
			            <th>name</th>
			            <th><%= @booker.user.name %></th>
			          </tr>
			          <tr>
			            <th>introduction</th>
			            <th><%= @booker.user.introduction %></th>
			          </tr>
			        </tbody>
			      </table>
				<div class="edit row">
					<% if user_signed_in? && @booker.user == current_user %>
					   <%= link_to edit_user_path(@user), class: 'col-xs-12 btn btn-default btn-block' do %>
				            <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
					   <% end %>
				    <% else %>
				   		<%= link_to user_path(current_user.id), class: 'col-xs-12 btn btn-default btn-block' do %>
				   		<span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
				   		<% end %>
					<% end %>
				</div>
			</div>
			<!-- New Books -->
			<div class="new-books">
				<h1>New book</h1>
				<%= form_for(@book) do |f| %>
				<!-- error message -->
				<% if @book.errors.any? %>
					<div id="error_explanation" class="alert alert-danger">
						<h2><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h2>
					  <ul>
					    <% @book.errors.full_messages.each do |message| %>
					      <li><%= message %></li>
					    <% end %>
					  </ul>
					</div>
				<% end %>
				<div class="book-form row">
					<label>Title</label>
					<%= f.text_field :title, class: "col-xs-12" %>
				</div>
				<div class="book-form row">
					<label>Option</label>
					<%= f.text_area :body, class: "col-xs-12" %>
				</div>
				<div class="book-form row">
					<%= f.submit "Create Book", class: "btn btn-primary col-xs-12" %>
				</div>
				<% end %>
			</div>
		</div>

		<div class="col-xs-9">
			<div class="users">
			  <h2>Book detail</h2>
			  <table class="table">
			    <tbody>
				      <tr>
				        <td><%= attachment_image_tag @booker.user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %><br>
				        	<%= link_to @booker.user.name, user_path(@booker.user.id) %>
				        </td>
				        <td><%= link_to @booker.title, book_path(@booker) %></td>
				        <td><%= @booker.body %></td>
				        <% if user_signed_in? && @booker.user == current_user %>
				        <td><%= link_to "Edit", edit_book_path(@booker), class: "btn btn-success" %></td>
				        <td><%= link_to "Destroy", book_path(@booker), class: "btn btn-danger", method: :delete %></td>
				        <% end %>
				      </tr>
			    </tbody>
			  </table>
			</div>
		</div>
	</div>

app/views/homes/about.html.erb
<div class="about">
	<h1>
		Welcome to <span class="glyphicon glyphicon-book"></span><strong>Booker</strong>
	</h1>
</div>

app/views/homes/top.html.erb
			<div class="row">
			 <div class="col-md-offset-3 col-md-6">
				<h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers !!</strong></h1>
				<p>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span></span>Bookers,<br>
					you can share and exchange your opinions, inpressions, and emotions<br>
					about various books!
				</p>

			</div>
		</div>


	   <div class="btn-wrapper">
	   		<div class="row">
				<div class=" col-xs-6 col-xs-offset-3">
					<%= link_to "Log in", new_user_session_path, class: 'btn btn-info  btn-group-justified' %>
				</div>
			</div>
			<div class="row">
				<div class=" col-xs-6 col-xs-offset-3">
					<%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-success  btn-group-justified' %>
				</div>
			</div>
	   </div>
		

	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header navbar navbar-fixed-top navbar-inverse">
      <div class="container">
      <nav class="nav navbar-nav navbar-left">
        <h2 class="headline">Bookers</h2>
      </nav>

          <nav>
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
              <li >
                <%= link_to "Home", mypage_path, class: "glyphicon glyphicon-home", 'aria-hidden' => true %>
              </li>
              <li>
                <%= link_to "Users", users_path, class: "glyphicon glyphicon-user", 'aria-hidden' => true %>
              </li>
              <li>
                <%= link_to "Books", books_path, class: "glyphicon glyphicon-book", 'aria-hidden' => true %>
              </li>
              <li>
                <%= link_to "logout", destroy_user_session_path, class: "glyphicon glyphicon-log-out", 'aria-hidden' => true,  method: :delete %>
              </li>
              <% else %>

                <li >
                  <%= link_to "Home", root_path, class: "glyphicon glyphicon-home", 'aria-hidden' => true %>
                </li>
                <li>
                  <%= link_to "About", home_about_path, class: "glyphicon glyphicon-link", 'aria-hidden' => true %>
                </li>
                <li>
                  <%= link_to "sign up", new_user_registration_path, class: "glyphicon glyphicon-edit", 'aria-hidden' => true %>
                </li>
                <li>
                  <%= link_to "login", new_user_session_path, class: "glyphicon glyphicon-share", 'aria-hidden' => true %>
                </li>

                <% end %>
            </ul>
          </nav>
      </div>
    </div>
    
    <div class="body">
      <div class="container">
        <p id="notice">
         <%=  notice %> 
        </p>
        <%= yield %>
      </div>
    </div>
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_sidemenu.html.erb
	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
			<!-- ユーザー -->
			<div class="user-profile">
				<div class="user-image"><%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></div>
				 <table class = "table">
			        <tbody>
			          <tr>
			            <th>name</th>
			            <th><%= @user.name %></th>
			          </tr>
			          <tr>
			            <th>introduction</th>
			            <th><%= @user.introduction %></th>
			          </tr>
			        </tbody>
			      </table>
				<div class="edit row">
					<% if user_signed_in? && @user == current_user %>
					   <%= link_to edit_user_path(@user), class: 'col-xs-12 btn btn-default btn-block' do %>
				            <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
					   <% end %>

					   <!-- ログインユーザー以外の編集ボタン -->
				   <% else %>
				   		<%= link_to user_path(current_user.id), class: 'col-xs-12 btn btn-default btn-block' do %>
				   		<span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
				   		<% end %>
					<% end %>
				</div>
			</div>
			<!-- New Books -->
			<div class="new-books">
				<h1>New book</h1>
				<%= form_for(@book) do |f| %>
				<!-- error message -->
				<% if @book.errors.any? %>
					<div id="error_explanation" class="alert alert-danger">
						<h2><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h2>
					  <ul>
					    <% @book.errors.full_messages.each do |message| %>
					      <li><%= message %></li>
					    <% end %>
					  </ul>
					</div>
				<% end %>
				<div class="book-form row">
					<label>Title</label>
					<%= f.text_field :title, class: "col-xs-12" %>
				</div>
				<div class="book-form row">
					<label>Option</label>
					<%= f.text_area :body, class: "col-xs-12" %>
				</div>
				<div class="book-form row">
					<%= f.submit "Create Book", class: "btn btn-primary col-xs-12" %>
				</div>
				<% end %>
			</div>
		</div>

app/views/users/edit.html.erb
	
		<div class="edit">
			<h2>User info</h2>
			<%= form_for(@user) do |f| %>

			<!-- error message -->
				<% if @user.errors.any? %>
					<div id="error_explanation" class="alert alert-danger">
						<h2><%= pluralize(@user.errors.count, "error") %> prohibited this product from being saved:</h2>
					  <ul>
					    <% @user.errors.full_messages.each do |message| %>
					      <li><%= message %></li>
					    <% end %>
					  </ul>
					</div>
				<% end %>

				 <div class="field">
			       <label>Name</label>
			       <%= f.text_field :name %>
			     </div>
			     <div class="field">
			       <label>Image</label>
			       <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
			     </div>
			  	 <div class="field">
			       <label>Introduction</label>
			       <%= f.text_area :introduction %>
			     </div>
			  	 <div><%= f.submit "Update User" %></div>

			<% end %>
		</div>
	

app/views/users/index.html.erb
<%= render 'users/sidemenu', {user:@user, book:@book} %>

		<div class="col-xs-9">
			<div class="users">
			  <h2>Users</h2>
			  <table class="table">
			    <thead>
			      <tr>
			        <th>image</th>
			        <th>name</th>
			        <th colspan="3"></th>
			      </tr>
			    </thead>
			    <tbody>
				    <% @users.each do |user| %>
				      <tr>
				        <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %></td>
				        <td><%= user.name %></td>
				        <td><%= link_to 'Show', user_path(user.id) %></td>
				      </tr>
				    <% end %>
			    </tbody>
			  </table>
			</div>
		</div>
	</div>

app/views/users/show.html.erb
<%= render 'users/sidemenu', {user:@user, book:@book} %>
		
		<div class="col-xs-9">
			<!-- 全ての本 -->
			<div class="books">
			  <h2>Books</h2>
			  <table class="table table-hover">
			    <thead>
			      <tr>
			        <th></th>
			        <th>Title</th>
			        <th>Opinion</th>
			      </tr>
			    </thead>
			    <tbody>
			    	<% @books.each do |book| %>
			      <tr>
			        <td><%= link_to user_path(@user) do %>
			        	<%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %>
			        	<% end %>
			        </td>
			        <td><%= link_to book.title, book_path(book.id) %></td>
			        <td><%= book.body %></td>
			      </tr>
			      <% end %>
			    </tbody>
			  </table>
			</div>

		</div>
	</div>